#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May  6 08:44:20 2026

@author: cwang
"""

import numpy as np

def read_iri_namelist_log(file_path) -> np.array :
    """
    Reads NaN log file generated by iri2020_namelist_driver.
    The results can actually be obtained from the python readout of
    the binary output. This code is to verify that the python read out is
    correct.

    Parameters
    ----------
    file_path : str
        Path to the file 

    Returns idx_iSample_iPts
    -------
 
    """
    idx_iSample_iPts=np.empty((0, 3), int) 
    with open(file_path, 'r') as f:
        line = f.readline()
        line = line[len("Ne contains NaN for sample, point"):]
        idx_iSample_iPts=np.append(idx_iSample_iPts,[int(x) for x in line.split()],axis=0)

    return idx_iSample_iPts


